There are 5 major components in a Pytorch model, which can be grouped into two classes, Storage and Transformers. (from the blog post- A comprehensive overiew of Pytorch).
Pytorch is an optimized tensor library for deep learning using GPU and TPU.(from Pytorch documentation)


torch.cuda.DtypeTensor defines a tensor wich Dtype as Byte, Char, Short, Int, Long, Half, Float, Double. A tensor is a multidimensional array of single data type.

In [0]:
import torch
import numpy as np
import pandas as pd

In [0]:
torch.tensor([[1,-1],[-1,1]])

tensor([[ 1, -1],
        [-1,  1]])

In [0]:
torch.as_tensor(np.array([[1,2,3],[4,5,6]])) #as_tensor does not copy data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [0]:
print(torch.cuda.is_available())

False


In [0]:
mytensor = torch.zeros([2,4])
mytensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
mytensor = torch.zeros([2,4], dtype=torch.int16)
mytensor

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16)

Use your favourite numpy or pandas like indexing to access the elements of the Tensor.

In [0]:
mytensor = torch.IntTensor([[1,2,3],[4,5,6],[7,8,9]])
mytensor[1,2]

tensor(6, dtype=torch.int32)

In [0]:
print(mytensor[0,1])
print(mytensor[1,1])
print(mytensor[1][1])
print(mytensor.shape)

tensor(2, dtype=torch.int32)
tensor(5, dtype=torch.int32)
tensor(5, dtype=torch.int32)
torch.Size([3, 3])


We can create Tensors of more than two dimensions. We create a tensor of three 2x2 matrices below.

In [0]:
mytensor = torch.IntTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(mytensor.shape)
print(mytensor[0][1][1])
print(mytensor[2][1][1])
mytensor[2,1,1] = 13
print(mytensor[2][1][1])
print(mytensor[1][0])
mytensor[1][0] = torch.IntTensor([20,21])
print(mytensor[1][0])

torch.Size([3, 2, 2])
tensor(4, dtype=torch.int32)
tensor(12, dtype=torch.int32)
tensor(13, dtype=torch.int32)
tensor([5, 6], dtype=torch.int32)
tensor([20, 21], dtype=torch.int32)


We have to follow datatypes with precision hierarchy or else be ready to lose precision

In [0]:
mytensor[1][0] = torch.FloatTensor([22.5,23.5])
print(mytensor[1])

tensor([[22, 23],
        [ 7,  8]], dtype=torch.int32)


Use .to() method to change the data type of the tensor.

In [0]:
newtensor = mytensor.to(torch.float32)
newtensor[1][0] = torch.FloatTensor([22.5,23.5])
print(newtensor[1])

tensor([[22.5000, 23.5000],
        [ 7.0000,  8.0000]])
