<a href="https://colab.research.google.com/github/cs17emds11029/googlecolab/blob/master/Pytorch_Learning_Two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The item method can be used to retrieve the underyling scalar as a python number

In [0]:
import torch
import numpy as np
import pandas as pd

In [0]:
mytensor = torch.Tensor([[1,1.5,2],[2,2.5,3]])
print(mytensor[0][0].item())

1.0


In [0]:
print(mytensor[0].item())

ValueError: ignored

Require gradient is a flag that can be passed to the Tensor constructor, which if True indicates operations on this tensor are recorded and gradient is calculated for the function operated on this tensor

In [12]:
mytensor = torch.tensor([[1,-1],[-1,1]],dtype=torch.float32,requires_grad=True)
print(mytensor) # from the doc

tensor([[ 1., -1.],
        [-1.,  1.]], requires_grad=True)


In [13]:
#perform an operation on this tensor
out = mytensor.pow(2).sum() #here out is evaluated to a scalar value, since the 
# the gradient is a differentiation over a scalar. 
print(out)

tensor(4., grad_fn=<SumBackward0>)


The output indicates that 'out' is a tensor with a gradient function and is created by a Sum operation, backward just indicates that its gradient will be calculated.

In [0]:
out.backward()

In [16]:
print(mytensor.grad)
print(out.grad)

tensor([[ 2., -2.],
        [-2.,  2.]])
None


Understanding how gradients are calculated is the crux of understand PyToch. Pytorch uses automatic differentiation by chain rule propogating the loss from the layer at the right most or latest layer to the left most or the first. This kind of layering helps to abstract to write code for the operations of back-propogation in a nueral network and concentrate on defining the structure of a network.

In [17]:
#lets test again
out = mytensor.pow(3)
print(out)

tensor([[ 1., -1.],
        [-1.,  1.]], grad_fn=<PowBackward0>)


In [18]:
out.backward()
print(mytensor.grad)
print(out.grad)

RuntimeError: ignored