<a href="https://colab.research.google.com/github/cs17emds11029/googlecolab/blob/master/Pytorch_Learning_Two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The item method can be used to retrieve the underyling scalar as a python number

In [0]:
import torch
import numpy as np
import pandas as pd

In [2]:
mytensor = torch.Tensor([[1,1.5,2],[2,2.5,3]])
print(mytensor[0][0].item())

1.0


In [3]:
print(mytensor[0].item())

ValueError: ignored

Require gradient is a flag that can be passed to the Tensor constructor, which if True indicates operations on this tensor are recorded and gradient is calculated for the function operated on this tensor

In [4]:
mytensor = torch.tensor([[1,-1],[-1,1]],dtype=torch.float32,requires_grad=True)
print(mytensor) # from the doc

tensor([[ 1., -1.],
        [-1.,  1.]], requires_grad=True)


In [5]:
#perform an operation on this tensor
out = mytensor.pow(2).sum() #here out is evaluated to a scalar value, since the 
# the gradient is a differentiation over a scalar. 
print(out)

tensor(4., grad_fn=<SumBackward0>)


The output indicates that 'out' is a tensor with a gradient function and is created by a Sum operation, backward just indicates that its gradient will be calculated.

In [0]:
out.backward()

In [7]:
print(mytensor.grad)
print(out.grad)

tensor([[ 2., -2.],
        [-2.,  2.]])
None


Understanding how gradients are calculated is the crux of understand PyToch. Pytorch uses automatic differentiation by chain rule propogating the loss from the layer at the right most or latest layer to the left most or the first. This kind of layering helps to abstract to write code for the operations of back-propogation in a nueral network and concentrate on defining the structure of a network.

In [15]:
#lets test again
out = mytensor.pow(3)
print(out)

tensor([[ 1., -1.],
        [-1.,  1.]], grad_fn=<PowBackward0>)


In [9]:
out.backward()
print(mytensor.grad)
print(out.grad)

RuntimeError: ignored

When the loss or output is no longer a scalar, then autograd does not work without arguments. You need to pass a vector/matrix (of ones unless your require weighted gradients with respect to the X's) with the same shape as the input X's to compute the Jacobian of Y with respect to the X's. The jacobian is the matrix of first order partial derivatives of 'out' with respect to the dimensions of 'mytensor'.

In [16]:
out = mytensor.pow(3)
out.backward(torch.ones(2,2))
print(mytensor.grad)
print(out.grad)

tensor([[10.4509, -1.8934],
        [-5.3596,  6.0457]])
None


So when you are designing a neural network, out is the output of the neural network architecture with respect to a single input. The loss is computed as the difference between groundtruth and out and the gradients wrt to the loss are compupted for each input. Then the parameters are adjusted immediately (SGD) or the gradients are accumulated over few inputs(batch or mini-batch GD) and then the parameters are updated. This is the framework for the nueral network. In the next notebook, we shall create a conv-net for image classification (or) a simple linear regression network. 